Shop/Shop/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^user/', include('user.urls', namespace='user')),
    url(r'^com/', include('commodity.urls', namespace='com')),
    url(r'^cart/', include('shopcart.urls', namespace='cart')),
    url(r'^order/', include('order.urls', namespace='order')),
    # 上传部件自动调用的上传地址
    url(r'^ckeditor/', include("ckeditor_uploader.urls")),
]

Shop/apps/commodity/urls.py
from django.conf.urls import url

from commodity.views import commodity_list, comcategory, index, city, village, tidings, recharge, yhq, ygq, speed, \
    s_list, detail, category

urlpatterns = [
    url('^index/$', index, name='首页'),
    url('^city/$', city, name='城市选择'),
    url('^village/$', village, name='校区选择'),
    url('^tidings/$', tidings, name='消息中心'),
    url('^recharge/$', recharge, name='充值'),
    url('^yhq/$', yhq, name='红包'),
    url('^ygq/$', ygq, name='过期红包'),
    url('^speed/$', speed, name='零食飞速'),
    url('^slist/$', s_list, name='琳琅的店'),
    url('^detail/(?P<id>\d+)/$', detail, name='商品详情'),
    url('^category/(?P<cate_id>\d*)_{1}(?P<order>\d?)\.html$', category, name='超市'),
    url('^commodity_list/$', commodity_list, name='商品列表'),
    url('^comcategory/$', comcategory, name='商品分类'),
]

Shop/apps/order/urls.py
from django.conf.urls import url

from order.views import tureorder, allorder

urlpatterns = [
   url(r'tureorder', tureorder, name='确认订单'),
   url(r'allorder', allorder, name='全部订单'),
]

Shop/apps/shopcart/urls.py
from django.conf.urls import url

from shopcart.views import shopcart

urlpatterns = [
    url('^shopcart/$', shopcart, name='购物车')
]

Shop/apps/user/urls.py
from django.conf.urls import url

from user.views import RegisterView, LoginView, message, member, step, infor, about, records, integral, \
    integralexchange, integralrecords, collect, collect_edit, gladdress, saftystep, payment, \
    boundphone, money, job, application, applicationjob, recommend, myrecommend, AddinfoView, AddressView, SendMsg, \
    PasswordView, ForgetView, release, messdetail

urlpatterns = [
    url(r'^register/$', RegisterView.as_view(), name='注册'),
    url(r'^login/$', LoginView.as_view(), name='登录'),
    url(r'^message/$', message, name='动态'),
    url(r'^release/$', release, name='发布动态'),
    url(r'^messdetail/$', messdetail, name='动态详情'),
    url(r'^member/$', member, name='我的详情'),
    url(r'^step/$', step, name='系统设置'),
    url(r'^infor/$', infor, name='个人资料'),
    url(r'^addinfor/$', AddinfoView.as_view(), name='修改个人资料'),
    url(r'^about/$', about, name='关于我们'),
    url(r'^records/$', records, name='账户余额'),
    url(r'^integral/$', integral, name='积分'),
    url(r'^integralexchange/$', integralexchange, name='积分兑换'),
    url(r'^integralrecords/$', integralrecords, name='兑换记录'),
    url(r'^collect/$', collect, name='我的收藏'),
    url(r'^collect_edit/$', collect_edit, name='我的收藏编辑'),
    url(r'^gladdress/$', gladdress, name='收货地址'),
    url(r'^address/$', AddressView.as_view(), name='新增收货地址'),
    url(r'^saftystep/$', saftystep, name='安全设置'),
    url(r'^password/$', PasswordView.as_view(), name='修改密码'),
    url(r'^payment/$', payment, name='支付密码'),
    url(r'^boundphone/$', boundphone, name='绑定手机'),
    url(r'^money/$', money, name='我的钱包'),
    url(r'^job/$', job, name='我要兼职'),
    url(r'^application/$', application, name='兼职申请记录'),
    url(r'^applicationjob/$', applicationjob, name='申请兼职'),
    url(r'^recommend/$', recommend, name='推荐有奖'),
    url(r'^myrecommend/$', myrecommend, name='我的推荐'),
    url(r'^sendMsg/$', SendMsg.as_view(), name='发送短消验证码'),
    url(r'^forgetpassword/$', ForgetView.as_view(), name='忘记密码'),
]

Shop/apps/commodity/models.py
from ckeditor_uploader.fields import RichTextUploadingField
from django.db import models

# Create your models here.
on_sale = (
    (True, '上架'),
    (False, '下架')
)


# 删除和创建修改时间的基础模型
class BasicsModel(models.Model):
    is_delete = models.BooleanField(default=False, verbose_name='删除')
    create_time = models.DateTimeField(auto_now_add=True, verbose_name='创建时间')
    update_time = models.DateTimeField(auto_now=True, verbose_name='修改时间')

    class Meta:
        # 设置为抽象类,不会被迁移
        abstract = True


# 商品分类表
class GoodsClassifyModel(BasicsModel):
    class_name = models.CharField(max_length=50, verbose_name='分类名称')
    class_intro = models.CharField(max_length=50, verbose_name='分类简介', null=True)
    order = models.SmallIntegerField(default=0, verbose_name="排序")

    def __str__(self):
        return self.class_name

    class Meta:
        db_table = 'goods_classify'
        verbose_name = '商品分类表'
        verbose_name_plural = verbose_name


# 商品SKU表
class GoodsSkuModel(BasicsModel):
    goods_name = models.CharField(max_length=200, verbose_name='商品名称')
    goods_intro = models.TextField(verbose_name='商品信息')
    price = models.DecimalField(decimal_places=2, max_digits=10, default=0, verbose_name='商品价格')
    unitinfo = models.ForeignKey(to='GoodsUnitModel', verbose_name='商品单位')
    num = models.PositiveIntegerField(verbose_name='商品库存')
    sell_num = models.PositiveIntegerField(verbose_name='商品销售量')
    logo = models.ImageField(upload_to='logo/%Y%m', verbose_name='商品图片')
    is_putaway = models.BooleanField(choices=on_sale, default=False, verbose_name='商品是否上架')
    goods_cate = models.ForeignKey(to='GoodsClassifyModel', verbose_name='商品分类')
    goods_spu = models.ForeignKey(to='SpuModel', verbose_name='商品spu分类')

    def __str__(self):
        return self.goods_name

    class Meta:
        db_table = 'goods_sku'
        verbose_name = '商品SKU表'
        verbose_name_plural = verbose_name


# 商品单位表
class GoodsUnitModel(BasicsModel):
    unit_name = models.CharField(max_length=50, verbose_name='单位名称')

    def __str__(self):
        return self.unit_name

    class Meta:
        db_table = 'goods_unit'
        verbose_name = '商品单位表'
        verbose_name_plural = verbose_name


# 商品spu表
class SpuModel(BasicsModel):
    spu_name = models.CharField(max_length=50, verbose_name='商品spu名称')
    spu_desc = RichTextUploadingField(verbose_name='商品spu描述')

    def __str__(self):
        return self.spu_name

    class Meta:
        db_table = 'goods_spu'
        verbose_name = '商品SPU表'
        verbose_name_plural = verbose_name


# 商品相册表
class GoodsAlbumModel(BasicsModel):
    album_image = models.ImageField(upload_to='album', verbose_name='商品图片地址')
    album_sku = models.ForeignKey(to='GoodsSkuModel', verbose_name='商品sku的ID')

    def __str__(self):
        return '商品相册'

    class Meta:
        db_table = 'goods_categories'
        verbose_name = '商品相册表'
        verbose_name_plural = verbose_name


# 首页轮播
class BannerModel(BasicsModel):
    banner_name = models.CharField(max_length=200, verbose_name='轮播活动名')
    banner_sku = models.ForeignKey(to='GoodsSkuModel', verbose_name='商品sku')
    banner_image = models.ImageField(upload_to='banner/%Y%m/%d', verbose_name='轮播图片地址')
    order = models.SmallIntegerField(default=0, verbose_name='排序')

    def __str__(self):
        return self.banner_name

    class Meta:
        db_table = 'banner'
        verbose_name = '首页轮播管理'
        verbose_name_plural = verbose_name


# 首页活动表
class ActivityModel(BasicsModel):
    title = models.CharField(max_length=200, verbose_name='活动名称')
    activity_image = models.ImageField(upload_to='activity/%Y%m/%d', verbose_name='活动图片地址')
    url = models.URLField(max_length=200, verbose_name='活动url地址')

    def __str__(self):
        return self.title

    class Meta:
        db_table = 'activity'
        verbose_name = '活动管理'
        verbose_name_plural = verbose_name


# 首页活动专区
class ActivityZoneModel(BasicsModel):
    title = models.CharField(max_length=200, verbose_name='活动专区名')
    brief = models.CharField(verbose_name="活动专区的简介",
                             max_length=200,
                             null=True,
                             blank=True,
                             )
    order = models.SmallIntegerField(verbose_name="排序",
                                     default=0,
                                     )
    is_on_sale = models.BooleanField(verbose_name="上否上线",
                                     choices=on_sale,
                                     default=0,
                                     )
    goods_sku = models.ForeignKey(to="GoodsSkuModel", verbose_name="商品")

    def __str__(self):
        return self.title

    class Meta:
        db_table = 'activity_zone'
        verbose_name = "活动专区管理"
        verbose_name_plural = verbose_name

Shop/apps/commodity/views.py
from django.shortcuts import render

from commodity.models import GoodsClassifyModel, BannerModel, GoodsSkuModel
from user.helper import check_login

# Create your views here.


# 首页
def index(request):
    banner = BannerModel.objects.all()
    data = GoodsSkuModel.objects.all()
    context = {
        'banner': banner,
        "data": data
    }
    return render(request, 'commodity/index.html', context=context)


# 首页左上城市选择
def city(request):
    return render(request, 'commodity/city.html')


# 首页校区选择
def village(request):
    return render(request, 'commodity/village.html')


# 首页消息中心
@check_login
def tidings(request):
    return render(request, 'commodity/tidings.html')


# 首页充值
@check_login
def recharge(request):
    return render(request, 'commodity/recharge.html')


# 首页红包
@check_login
def yhq(request):
    return render(request, 'commodity/yhq.html')


# 过期红包
@check_login
def ygq(request):
    return render(request, 'commodity/ygq.html')


# 首页零食飞速
def speed(request):
    return render(request, 'commodity/speed.html')


# 飞速零食中七米设计零食屋
def s_list(request):
    return render(request, 'commodity/list.html')


# 商品详情
def detail(request, id):
    data = GoodsSkuModel.objects.get(pk=id)
    context = {
        'data': data
    }
    return render(request, 'commodity/detail.html', context=context)


# 超市
def category(request, cate_id, order):
    # 查询分类名称
    classify = GoodsClassifyModel.objects.filter(is_delete=False).order_by('-order')
    # 查询第一个分类
    if cate_id == '':
        data = classify.first()
        cate_id = data.pk
    else:
        # 根据分类id查询对应的分类
        cate_id = int(cate_id)
        data = GoodsClassifyModel.objects.get(pk=cate_id)
    # 查询对应分类下所有的商品
    goods = GoodsSkuModel.objects.filter(is_delete=False, goods_cate=data)
    # 查询商品SKU详情
    # data = GoodsSkuModel.objects.all()
    # 排序
    if order == '':
        order = 0
    order = int(order)
    # if order == 0:
    #     goods = goods.order_by("pk")
    # elif order == 1:
    #     goods = goods.order_by("-sell_num")
    # elif order == 2:
    #     goods = goods.order_by("price")
    # elif order == 3:
    #     goods = goods.order_by("-price")
    # elif order == 4:
    #     goods = goods.order_by("-create_time")

    # 排序规则列表
    order_rule = ['pk', '-sell_num', 'price', '-price', '-create_time']
    goods = goods.order_by(order_rule[order])
    context = {
        'classify': classify,
        'goods': goods,
        'cate_id': cate_id,
        'order': order,
    }
    return render(request, 'commodity/category.html', context=context)


# 商品列表
def commodity_list(request):
    return render(request, 'commodity/list.html')


# 商品分类
def comcategory(request):
    return render(request, 'commodity/category.html')

Shop/templates/commodity/city.html
{% extends 'common/parent.html' %}
{% load static %}

{% block content %}
<body>
		<header data-am-widget="header" class="am-header am-header-default sq-head ">
			<div class="am-header-left am-header-nav">
				<a href="javascript:history.back()" class="">
					<i class="am-icon-chevron-left"></i>
				</a>
			</div>
			<h1 class="am-header-title">
  	            <a href="" class="">选择城市</a>
            </h1>
	    </header>
	    <div style="height: 49px;"></div>
	    <ul class="city-list">
	    	<li class="curr"><a href="{% url 'com:首页' %}">南昌</a></li>
	    	<li><a href="{% url 'com:首页' %}">长沙</a></li>
	    	<li><a href="{% url 'com:首页' %}">北京</a></li>
	    </ul>
{% endblock %}

Shop/templates/commodity/index.html
{% extends 'common/parent.html' %}
{% load static %}

{% block content %}
    <body>
    <header data-am-widget="header" class="am-header am-header-default sq-head1">
        <div class="am-header-left am-header-nav">
            <a href="" class="" style="color: #fff;">
                <img src="{% static 'images/city.png' %}"/>
                <p style="font-size: 12px; margin-top: -35px;" id="info">全国</p>
            </a>
        </div>
        <h1 class="am-header-title1">
            <div class="search-box">
                <a href="{% url 'com:校区选择' %}" class="index-search">南昌大学前湖校区∨</a>
                <!--  <input type="submit" value="" class="search-icon" /> -->
            </div>
        </h1>
        <div class="am-header-right am-header-nav">
            <a href="{% url 'com:消息中心' %}" class="">
                <div class="messgae"><span>10</span></div>
            </a>
        </div>
    </header>
    <div style="height: 49px;"></div>
    <!--图片轮换-->
    <div class="am-slider am-slider-default" data-am-flexslider id="demo-slider-0">
        <ul class="am-slides">
            {% for v in banner %}
                <li><img src="{{ MEDIA_URL }}{{ v.banner_image }}"/></li>
            {% endfor %}
            {#    <li><img src="{% static 'images/banner.png' %}" /></li>#}
            {#    <li><img src="{% static 'images/banner.png' %}" /></li>#}
        </ul>
    </div>
    <!--导航-->
    <ul class="sq-nav">
        <li>
            <div class="am-gallery-item">
                <a href="{% url 'com:充值' %}" class="">
                    <img src="{% static 'images/icon.png' %}"/>
                    <p>充值</p>
                </a>
            </div>
        </li>
        <li>
            <div class="am-gallery-item">
                <a href="javascript:;" class="index-qd">
                    <img src="{% static 'images/icon1.png' %}"/>
                    <p>签到</p>
                </a>
            </div>
        </li>
        <li>
            <div class="am-gallery-item">
                <a href="{% url 'com:红包' %}" class="">
                    <img src="{% static 'images/icon2.png' %}"/>
                    <p>红包</p>
                </a>
            </div>
        </li>
        <li>
            <div class="am-gallery-item">
                <a href="" class="">
                    <img src="{% static 'images/icon3.png' %}"/>
                    <p>即将上线</p>
                </a>
            </div>
        </li>
    </ul>
    <ul class="sq-nav1">
        <li>
            <div class="am-gallery-item">
                <a href="{% url 'com:零食飞速' %}" class="">
                    <img src="{% static 'images/icon4.png' %}"/>
                    <p>零食飞速</p>
                </a>
            </div>
        </li>
        <li>
            <div class="am-gallery-item">
                <a href="{% url 'com:超市' '' '' %}" class="">
                    <img src="{% static 'images/icon5.png' %}"/>
                    <p>超市</p>
                </a>
            </div>
        </li>

    </ul>
    <div class="h-line"></div>
    <!--不规则展示-->
    <div class="index-product">
        <div class="index-pro-lf"><a href=""><img src="{% static 'images/s1.png' %}"/></a></div>
        <div class="index-pro-lr"><a href=""><img src="{% static 'images/s2.png' %}"/></a></div>
    </div>
    <div class="product-bot">
        <div class="product-bot-lf"><a href=""><img src="{% static 'images/s3.png' %}"/></a></div>
        <div class="product-bot-lr">
            <div class="top"><a href=""><img src="{% static 'images/s4.png' %}"/></a></div>
            <div class="bot">
                <div class="bot-lf"><a href=""><img src="{% static 'images/s5.png' %}"/></a></div>
                <div class="bot-lr"><a href=""><img src="{% static 'images/s6.png' %}"/></a></div>
            </div>
        </div>
    </div>
    <!--不规则展示-->
    <div class="h-line"></div>
    <!-- 特色专区-->


    <div class="sq-title">
        <img src="{% static 'images/ts.png' %}" width="26"/>
        特色专区
    </div>
    <ul data-am-widget="gallery" class="am-gallery pro-list am-avg-sm-2 am-avg-md-2 am-avg-lg-4 am-gallery-default">
        {% for data in data %}
            <li>
                <div class="am-gallery-item">
                    <a href="{% url 'com:商品详情' data.pk %}" class="">
                    <img src="{{ MEDIA_URL }}{{ data.logo }}"/>
                    <h3 class="am-gallery-title">{{ data.goods_spu.spu_name }}{{ data.goods_name }}</h3>
                    <div class="am-gallery-desc">{{ data.price }}</div>
                    </a>
                </div>
            </li>
        {% endfor %}


    </ul>
    <!--签到-->
    <div class="qd-box">
        <div class="popup-title">
            <span>签到成功</span>
            <div class="popup-close"><i class="iconfont">&#xe602</i></div>
        </div>
        <div class="dq-text">
            <img src="{% static 'images/qiandao.png' %}" width="40"/>&nbsp; 您已连续签到3天
        </div>
    </div>
    <!--签到-->

    <!--底部-->
    <div style="height: 55px;"></div>
    <div data-am-widget="navbar" class="am-navbar am-cf am-navbar-default sq-foot am-no-layout" id="">
        <ul class="am-navbar-nav am-cf am-avg-sm-5">
            <li>
                <a href="{% url 'com:首页' %}" class="curr">
                    <span class="am-icon-home"></span>
                    <span class="am-navbar-label">首页</span>
                </a>
            </li>
            <li>
                <a href="{% url 'user:动态' %}" class="">
                    <span class="am-icon-comments"></span>
                    <span class="am-navbar-label">动态</span>
                </a>
            </li>
            <li>
                <a href="{% url 'cart:购物车' %}" class="">
                    <span class="am-icon-shopping-cart"></span>
                    <span class="am-navbar-label">购物车</span>
                </a>
            </li>
            <li>
                <a href="{% url 'order:全部订单' %}" class="">
                    <span class="am-icon-file-text"></span>
                    <span class="am-navbar-label">订单</span>
                </a>
            </li>

            <li>
                <a href="{% url 'user:我的详情' %}" class="">
                    <span class="am-icon-user"></span>
                    <span class="am-navbar-label">我的</span>
                </a>
            </li>
        </ul>
    </div>


    <script type='text/javascript'>
        (function () {
            new PopUp_api({el: '.index-qd', html: '.qd-box'});
        })()
    </script>

    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/amazeui.min.js' %}"></script>
    </body>
{% endblock %}

{% block footer %}
<script type="text/javascript" src="https://webapi.amap.com/maps?v=1.4.12&key=67593cf5ed6a719c1c2bed20634a264a&plugin=AMap.CitySearch"></script>
    <script type="text/javascript">

    //获取用户所在城市信息
    function showCityInfo() {
        //实例化城市查询类
        var citysearch = new AMap.CitySearch();
        //自动获取用户IP，返回当前城市
        citysearch.getLocalCity(function(status, result) {
            if (status === 'complete' && result.info === 'OK') {
                if (result && result.city && result.bounds) {
                    var cityinfo = result.city;
                    var citybounds = result.bounds;
                    document.getElementById('info').innerHTML = cityinfo;
                    //地图显示当前城市
                    map.setBounds(citybounds);
                }
            } else {
                document.getElementById('info').innerHTML = result.info;
            }
        });
    }
    showCityInfo();
</script>
{% endblock %}

Shop/templates/commodity/speed.html
{% extends 'common/parent.html' %}
{% load static %}

{% block content %}

    <body>
		<header data-am-widget="header" class="am-header am-header-default sq-head ">
			<div class="am-header-left am-header-nav">
				<a href="javascript:history.back()" class="">
					<i class="am-icon-chevron-left"></i>
				</a>
			</div>
			<h1 class="am-header-title">
  	            <a href="" class="">零食飞速</a>
            </h1>
	    </header>
	    <div style="height: 49px;"></div>
	    <div class="school">您当前位于：江西现代职业技术学院</div>
	    <div class="content-list">
	    	<div class="list-left" style="top: 90px;">
	    		<li><a href="">学生公寓</a></li>
	    		<li class="current"><a href="">教学楼</a></li>
	    		<li><a href="">食堂</a></li>
	    	</div>
	    	<div class="list-right" style="padding-top: 50px;">
	    		<ul data-am-widget="gallery" class="am-gallery am-avg-sm-2 am-avg-md-2 am-avg-lg-4 am-gallery-default am-no-layout">
				      <li>
				        <div class="am-gallery-item">
				            <a href="{% url 'com:琳琅的店' %}" class="">
				              <img src=" {% static 'images/shop1.png' %}">
				                <h3 class="am-gallery-title">七米设计零食屋</h3>
				            </a>
				            <i class="speed-xin">营业中</i>
				        </div>
				      </li>
				      <li>
				        <div class="am-gallery-item">
				            <a href="{% url 'com:琳琅的店' %}" class="">
				              <img src=" {% static 'images/shop2.png' %}">
				                <h3 class="am-gallery-title">琳琅的店</h3>
				            </a>
				            <i class="speed-xin">营业中</i>
				        </div>
				      </li>
				      <li>
				        <div class="am-gallery-item">
				            <a href="{% url 'com:琳琅的店' %}" class="">
				              <img src=" {% static 'images/shop3.png' %}">
				                <h3 class="am-gallery-title">小米妈妈的店</h3>
				            </a>
				            <i class="speed-xin">营业中</i>
				        </div>
				      </li>
				      <li>
				        <div class="am-gallery-item">
				            <a href="{% url 'com:琳琅的店' %}" class="">
				              <img src=" {% static 'images/shop4.png' %}">
				                <h3 class="am-gallery-title">爱果果</h3>
				            </a>
				            <i class="speed-xin1">偷懒中</i>
				        </div>
				      </li>

				</ul>
	    	</div>
	    </div>

	   <!--底部-->
 <div style="height: 55px;"></div>
 <div data-am-widget="navbar" class="am-navbar am-cf am-navbar-default sq-foot am-no-layout" id="">
      <ul class="am-navbar-nav am-cf am-avg-sm-5">
          <li>
            <a href="{% url 'com:首页' %}" class="curr">
                <span class="am-icon-home"></span>
                <span class="am-navbar-label">首页</span>
            </a>
          </li>
          <li>
            <a href="{% url 'user:动态' %}" class="">
                <span class="am-icon-comments"></span>
                <span class="am-navbar-label">动态</span>
            </a>
          </li>
          <li>
            <a href="{% url 'cart:购物车' %}" class="">
                <span class="am-icon-shopping-cart"></span>
                <span class="am-navbar-label">购物车</span>
            </a>
          </li>
          <li>
            <a href="{% url 'order:全部订单' %}" class="">
                <span class="am-icon-file-text"></span>
                <span class="am-navbar-label">订单</span>
            </a>
          </li>

          <li>
            <a href="{% url 'user:我的详情' %}" class="">
                <span class="am-icon-user"></span>
                <span class="am-navbar-label">我的</span>
            </a>
          </li>
      </ul>
</div>



<script src="{% static 'js/jquery.min.js' %}"></script>
<script src="{% static 'js/amazeui.min.js' %}"></script>
	</body>

{% endblock %}

Shop/templates/commodity/ygq.html
{% extends 'common/parent.html' %}
{% load static %}

{% block content %}

    <body style="background: #efefef;">
		<header data-am-widget="header" class="am-header am-header-default sq-head ">
			<div class="am-header-left am-header-nav">
				<a href="javascript:history.back()" class="">
					<i class="am-icon-chevron-left"></i>
				</a>
			</div>
			<h1 class="am-header-title">
  	            <a href="" class="">我的红包</a>
            </h1>
	    </header>
	    <div style="height: 49px;"></div>
	    <div class="whitebar">
	    <div data-am-widget="tabs" class="am-tabs am-tabs-d2">
			<ul class="am-tabs-nav am-cf" style="position: fixed; top: 49px;">
			    <li class=""><a href="{% url 'com:红包' %}">可使用</a></li>
			    <li class=""><a href="">已使用</a></li>
			    <li class="am-active"><a href="{% url 'com:过期红包' %}">已过期</a></li>
			</ul>
			<div style="height: 49px;"></div>
		</div>
		</div>
		<ul class="yhq">
		   	<li class="yhq-gq">
		   		<a href="">
		   		<div class="price">
		   			<span>￥3.9</span>
		   			<p>订单满￥20.0可用</p>
		   		</div>
		   		<div class="text">
		   			<p class="info">购物满20减3.9</p>
		   			<p style="font-size: 1.2rem; color: #807f80;">（仅限超市使用）</p>
		   			<p class="user">全国（使用地区）</p>
		   			<p class="time">2016-01-01—2016-01-31</p>
		   		</div>
		   		<div class="gy-pic"><img src="{% static 'images/guoqi.png' %}"/></div>
		   		</a>
		   	</li>

		</ul>
	</body>

{% endblock %}

Shop/templates/commodity/yhq.html
{% extends 'common/parent.html' %}
{% load static %}

{% block content %}

    <body style="background: #efefef;">
		<header data-am-widget="header" class="am-header am-header-default sq-head ">
			<div class="am-header-left am-header-nav">
				<a href="javascript:history.back()" class="">
					<i class="am-icon-chevron-left"></i>
				</a>
			</div>
			<h1 class="am-header-title">
  	            <a href="" class="">我的红包</a>
            </h1>
	    </header>
	    <div style="height: 49px;"></div>
	    <div class="whitebar">
	    <div data-am-widget="tabs" class="am-tabs am-tabs-d2">
			<ul class="am-tabs-nav am-cf" style="position: fixed; top: 49px;">
			    <li class="am-active"><a href="{% url 'com:红包' %}">可使用</a></li>
			    <li class=""><a href="">已使用</a></li>
			    <li class=""><a href="{% url 'com:过期红包' %}">已过期</a></li>
			</ul>
			<div style="height: 49px;"></div>
		</div>
		</div>
		<ul class="yhq">
		   	<li class="yhq-pic">
		   		<a href="">
		   		<div class="price">
		   			<span>￥3.9</span>
		   			<p>订单满￥20.0可用</p>
		   		</div>
		   		<div class="text">
		   			<p class="info">购物满20减3.9</p>
		   			<p style="font-size: 1.2rem; color: #807f80;">（仅限超市使用）</p>
		   			<p class="user">全国（使用地区）</p>
		   			<p class="time">2016-01-01—2016-01-31</p>
		   		</div>
		   		</a>
		   	</li>
		   	<li class="yhq-pic">
		   		<a href="">
		   		<div class="price">
		   			<span>￥3.9</span>
		   			<p>订单满￥20.0可用</p>
		   		</div>
		   		<div class="text">
		   			<p class="info">购物满20减3.9</p>
		   			<p style="font-size: 1.2rem; color: #807f80;">（仅限超市使用）</p>
		   			<p class="user">全国（使用地区）</p>
		   			<p class="time">2016-01-01—2016-01-31</p>
		   		</div>
		   		</a>
		   	</li>
		   	<li class="yhq-pic">
		   		<a href="">
		   		<div class="price">
		   			<span>￥3.9</span>
		   			<p>订单满￥20.0可用</p>
		   		</div>
		   		<div class="text">
		   			<p class="info">购物满20减3.9</p>
		   			<p style="font-size: 1.2rem; color: #807f80;">（仅限超市使用）</p>
		   			<p class="user">全国（使用地区）</p>
		   			<p class="time">2016-01-01—2016-01-31</p>
		   		</div>
		   		</a>
		   	</li>
		</ul>
	</body>

{% endblock %}