Shop/Shop/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^user/', include('user.urls', namespace='user')),
    url(r'^com/', include('commodity.urls', namespace='com')),
    url(r'^cart/', include('shopcart.urls', namespace='cart')),
    url(r'^order/', include('order.urls', namespace='order')),
    # 上传部件自动调用的上传地址
    url(r'^ckeditor/', include("ckeditor_uploader.urls")),
]

Shop/apps/commodity/urls.py
from django.conf.urls import url

from commodity.views import commodity_list, comcategory, index, city, village, tidings, recharge, yhq, ygq, speed, \
    s_list, detail, category

urlpatterns = [
    url('^index/$', index, name='首页'),
    url('^city/$', city, name='城市选择'),
    url('^village/$', village, name='校区选择'),
    url('^tidings/$', tidings, name='消息中心'),
    url('^recharge/$', recharge, name='充值'),
    url('^yhq/$', yhq, name='红包'),
    url('^ygq/$', ygq, name='过期红包'),
    url('^speed/$', speed, name='零食飞速'),
    url('^slist/$', s_list, name='琳琅的店'),
    url('^detail/(?P<id>\d+)/$', detail, name='商品详情'),
    url('^category/(?P<cate_id>\d*)_{1}(?P<order>\d?)\.html$', category, name='超市'),
    url('^commodity_list/$', commodity_list, name='商品列表'),
    url('^comcategory/$', comcategory, name='商品分类'),
]

Shop/apps/order/urls.py
from django.conf.urls import url

from order.views import tureorder, allorder

urlpatterns = [
   url(r'tureorder', tureorder, name='确认订单'),
   url(r'allorder', allorder, name='全部订单'),
]

Shop/apps/shopcart/urls.py
from django.conf.urls import url

from shopcart.views import shopcart

urlpatterns = [
    url('^shopcart/$', shopcart, name='购物车')
]

Shop/apps/user/urls.py
from django.conf.urls import url

from user.views import RegisterView, LoginView, message, member, step, infor, about, records, integral, \
    integralexchange, integralrecords, collect, collect_edit, gladdress, saftystep, payment, \
    boundphone, money, job, application, applicationjob, recommend, myrecommend, AddinfoView, AddressView, SendMsg, \
    PasswordView, ForgetView, release, messdetail

urlpatterns = [
    url(r'^register/$', RegisterView.as_view(), name='注册'),
    url(r'^login/$', LoginView.as_view(), name='登录'),
    url(r'^message/$', message, name='动态'),
    url(r'^release/$', release, name='发布动态'),
    url(r'^messdetail/$', messdetail, name='动态详情'),
    url(r'^member/$', member, name='我的详情'),
    url(r'^step/$', step, name='系统设置'),
    url(r'^infor/$', infor, name='个人资料'),
    url(r'^addinfor/$', AddinfoView.as_view(), name='修改个人资料'),
    url(r'^about/$', about, name='关于我们'),
    url(r'^records/$', records, name='账户余额'),
    url(r'^integral/$', integral, name='积分'),
    url(r'^integralexchange/$', integralexchange, name='积分兑换'),
    url(r'^integralrecords/$', integralrecords, name='兑换记录'),
    url(r'^collect/$', collect, name='我的收藏'),
    url(r'^collect_edit/$', collect_edit, name='我的收藏编辑'),
    url(r'^gladdress/$', gladdress, name='收货地址'),
    url(r'^address/$', AddressView.as_view(), name='新增收货地址'),
    url(r'^saftystep/$', saftystep, name='安全设置'),
    url(r'^password/$', PasswordView.as_view(), name='修改密码'),
    url(r'^payment/$', payment, name='支付密码'),
    url(r'^boundphone/$', boundphone, name='绑定手机'),
    url(r'^money/$', money, name='我的钱包'),
    url(r'^job/$', job, name='我要兼职'),
    url(r'^application/$', application, name='兼职申请记录'),
    url(r'^applicationjob/$', applicationjob, name='申请兼职'),
    url(r'^recommend/$', recommend, name='推荐有奖'),
    url(r'^myrecommend/$', myrecommend, name='我的推荐'),
    url(r'^sendMsg/$', SendMsg.as_view(), name='发送短消验证码'),
    url(r'^forgetpassword/$', ForgetView.as_view(), name='忘记密码'),
]

Shop/user/urls.py
from django.conf.urls import url

from Shop.user.views import RegisterView, LoginView

urlpatterns = [
    url(r'^register/$', RegisterView.as_view(), name='注册'),
    url(r'^login/$', LoginView.as_view(), name='登录'),
]

Shop/apps/user/models.py
from django.core.validators import MinLengthValidator, RegexValidator
from django.db import models


# Create your models here.

class Users(models.Model):
    gender_choices = (
        (1, '男'),
        (2, '女'),
        (3, '保密'),
    )
    phone = models.CharField(max_length=11,
                             validators=[
                                 MinLengthValidator(11, '手机号长度不正确'),
                                 RegexValidator(r'^1[3-9]\d{9}$', '手机号码格式不正确')
                             ], verbose_name='手机号码')
    user_name = models.CharField(max_length=16,
                                 validators=[
                                     MinLengthValidator(4, '昵称最少有4个字符')
                                 ], null=True, verbose_name='昵称'
                                 )
    password = models.CharField(max_length=32, verbose_name='密码')
    gender = models.SmallIntegerField(choices=gender_choices, default=3, verbose_name='性别')
    birthday = models.DateField(null=True, verbose_name='生日')
    school = models.CharField(max_length=100, null=True, verbose_name='学校')
    address = models.CharField(max_length=200, null=True, verbose_name='详细地址')
    hometown = models.CharField(max_length=100, null=True, verbose_name='老家')

    is_delete = models.BooleanField(default=False, verbose_name='删除')
    create_time = models.DateTimeField(auto_now_add=True, verbose_name='创建时间')
    update_time = models.DateTimeField(auto_now=True, verbose_name='修改时间')

    # 设置头像
    head = models.ImageField(upload_to='head/%Y%m', default='head/memtx.png')

    def __str__(self):
        return self.user_name

    class Meta:
        db_table = 'users'


class Address(models.Model):
    name = models.CharField(max_length=50, verbose_name='收货人姓名')
    telephone = models.CharField(max_length=11,
                                 validators=[
                                     MinLengthValidator(11, '手机号长度不正确'),
                                     RegexValidator(r'^1[3-9]\d{9}$', '手机号码格式不正确')
                                 ], verbose_name='手机号码')
    province = models.CharField(max_length=50, verbose_name='省份')
    city = models.CharField(max_length=50, verbose_name='城市')
    area = models.CharField(max_length=50, verbose_name='地区')
    brief = models.CharField(max_length=50, verbose_name='详细地址')
    # id_users = models.ForeignKey(to='Users', verbose_name='用户id')

    is_difault = models.BooleanField(default=False, verbose_name='默认地址')
    is_delete = models.BooleanField(default=False, verbose_name='删除')
    create_time = models.DateTimeField(auto_now_add=True, verbose_name='创建时间')
    update_time = models.DateTimeField(auto_now=True, verbose_name='修改时间')

    def __str__(self):
        return self.name

    class Meta:
        db_table = 'address'

Shop/apps/user/views.py
import random
import uuid

from django_redis import get_redis_connection
from django.http import JsonResponse, HttpResponse
from django.shortcuts import render, redirect
import re
from user.helper import check_login, send_sms, login
from user.models import Users, Address
# Create your views here.
from django.views import View
from user.forms import RegisterModelForm, LoginModelForm, InforModelForm, AddressModelForm, PasswordModelForm, \
    ForgetModelForm
from user import set_password


# 定义注册页面的视图类
class RegisterView(View):

    def get(self, request):
        # 跳转注册表单
        return render(request, 'user/reg.html')

    def post(self, request):  # 注册页面视图
        # 接收参数
        data = request.POST
        # 表单验证合法
        form = RegisterModelForm(data)
        if form.is_valid():
            # 操作数据库
            clened_data = form.cleaned_data
            # 创建一个用户
            user = Users()
            user.phone = clened_data.get('phone')
            user.password = set_password(clened_data.get('password'))
            user.save()
            return redirect('user:登录')
        # 错误
        else:
            return render(request, 'user/reg.html', context={'form': form})


# 定义登录页面的视图类
class LoginView(View):
    def get(self, request):
        # 跳转登录页面
        return render(request, 'user/login.html')

    def post(self, request):
        # 接收参数
        data = request.POST
        # 表单验证合法
        form = LoginModelForm(data)
        if form.is_valid():
            user = form.cleaned_data.get('user')
            request.session['ID'] = user.pk
            request.session['phone'] = user.phone
            return redirect('com:首页')
        else:
            return render(request, 'user/login.html', context={'form': form})


# 手机短信验证
class SendMsg(View):
    def get(self):
        pass

    def post(self, request):
        # 接收参数
        phone = request.POST.get('phone', '')
        rs = re.search('^1[3-9]\d{9}$', phone)
        # 判断参数的合法性
        if rs is None:
            return JsonResponse({'error': 1, 'errmsg': '电话号码格式不正确!'})
        # 生成随机验证码字符串
        random_code = ''.join([str(random.randint(0, 9)) for _ in range(6)])
        print('随机验证码为:{}'.format(random_code))

        # 保存验证码到redis中
        # 获取连接
        r = get_redis_connection()
        r.set(phone, random_code)
        # 设置60秒后过期
        r.expire(phone, 60)
        # 先获取当前手机号码的发送次数
        key_times = '{}_times'.format(phone)
        now_times = r.get(key_times)  # 是二进制内容,需要转换
        if now_times is None or int(now_times) < 5:
            # 保存手机号发送验证码的次数,不能超过5次
            r.incr(key_times)
            # 设置一个过期时间
            r.expire(key_times, 3600)  # 一个小时后再发送
        else:
            # 返回错误
            return JsonResponse({'error': 1, 'errmsg': '发送次数过多'})

        # # 连接运营商
        # __business_id = uuid.uuid1()
        # params = "{\"code\":\"%s\",\"product\":\"用户注册\"}" % random_code
        # # print(params)
        # rs = send_sms(__business_id, phone, "注册验证", "SMS_2245271", params)
        # print(rs.decode('utf-8'))
        # 合成响应
        return JsonResponse({'error': 0})


# 动态
@check_login
def message(request):
    return render(request, 'user/message.html')


# 发布动态
@check_login
def release(request):
    return render(request, 'user/release.html')


# 动态详情
@check_login
def messdetail(request):
    return render(request, 'user/messdetail.html')


# 我的详情
@check_login
def member(request):
    return render(request, 'user/member.html')


# 系统设置
@check_login
def step(request):
    return render(request, 'user/step.html')


# 个人资料
@check_login
def infor(request):
    id = request.session.get('ID')
    # 查询数据库
    data = Users.objects.filter(pk=id)
    # print(data)
    context = {
        'data': data
    }
    return render(request, 'user/infor.html', context=context)


# 修改个人资料
class AddinfoView(View):
    def get(self, request):
        # 跳转编辑个人资料页面
        return render(request, 'user/addinfor.html')

    def post(self, request):
        id = request.session.get('ID')
        # 接受参数
        data = request.POST
        head = request.FILES.get('head')
        user = Users.objects.get(pk=id)
        if head is not None:
            user.head = head
            user.save()
        login(request, user)
        # 表单验证合法
        form = InforModelForm(data, instance=user)
        if form.is_valid():
            form.save()
            return redirect('user:个人资料')
        else:
            # 提示错误
            context = {
                'form': form
            }
            return render(request, 'user/addinfor.html', context=context)

# 关于我们
@check_login
def about(request):
    return render(request, 'user/about.html')


# 账户余额
@check_login
def records(request):
    return render(request, 'user/records.html')


# 积分
@check_login
def integral(request):
    return render(request, 'user/integral.html')


# 积分兑换
@check_login
def integralexchange(request):
    return render(request, 'user/integralexchange.html')


# 兑换记录
@check_login
def integralrecords(request):
    return render(request, 'user/integralrecords.html')


# 我的收藏
@check_login
def collect(request):
    return render(request, 'user/collect.html')


# 我的收藏编辑
@check_login
def collect_edit(request):
    return render(request, 'user/collect-edit.html')


# 收货地址
@check_login
def gladdress(request):
    # 查询数据库
    data = Address.objects.all()
    print(data)
    context = {
        'data': data
    }
    return render(request, 'user/gladdress.html', context=context)


# 新增收货地址
class AddressView(View):
    def get(self, request):
        # 跳转增加收货地址表单
        return render(request, 'user/address.html')

    def post(self, request):
        # 接收参数
        data = request.POST
        # 表单验证合法
        form = AddressModelForm(data)
        if form.is_valid():
            form.save()
            return redirect('user:收货地址')
        # 错误
        else:
            return render(request, 'user/address.html', context={'form': form})


# 安全设置
@check_login
def saftystep(request):
    return render(request, 'user/saftystep.html')


# 修改密码
class PasswordView(View):
    def get(self, request):
        return render(request, 'user/password.html')

    def post(self, request):
        id = request.session.get('ID')
        # print(id)
        # 接受参数
        data = request.POST
        user = Users.objects.get(pk=id)
        # 表单验证合法
        form = PasswordModelForm(data, instance=user)
        if form.is_valid():
            form.save()
            return redirect('user:安全设置')
        else:
            # 提示错误
            context = {
                'form': form
            }
            return render(request, 'user/password.html', context=context)
# @check_login
# def password(request):
#     return render(request, 'user/password.html')


# 忘记密码
class ForgetView(View):
    def get(self, request):
        return render(request, 'user/forgetpassword.html')

    def post(self, request):
        # print(id)
        # 接受参数
        data = request.POST
        phone = data.get('phone')
        user = Users.objects.get(phone=phone)
        # 表单验证合法
        form = ForgetModelForm(data, instance=user)
        if form.is_valid():
            clened_data = form.cleaned_data
            user.password = set_password(clened_data.get('password'))
            user.save()
            return redirect('user:登录')
        else:
            # 提示错误
            context = {
                'form': form
            }
            return render(request, 'user/forgetpassword.html', context=context)
# def forgetpassword(request):
#     return render(request, 'user/forgetpassword.html')


# 支付密码
@check_login
def payment(request):
    return render(request, 'user/payment.html')


# 绑定手机
@check_login
def boundphone(request):
    return render(request, 'user/boundphone.html')


# 我的钱包
@check_login
def money(request):
    return render(request, 'user/money.html')


# 我要兼职
@check_login
def job(request):
    return render(request, 'user/job.html')


# 兼职申请记录
@check_login
def application(request):
    return render(request, 'user/application.html')


# 申请兼职
@check_login
def applicationjob(request):
    return render(request, 'user/applicationjob.html')


# 推荐有奖
@check_login
def recommend(request):
    return render(request, 'user/recommend.html')


# 我的推荐
@check_login
def myrecommend(request):
    return render(request, 'user/myrecommend.html')

Shop/user/views.py
from django.shortcuts import render, redirect
from Shop.user.models import Users
# Create your views here.
from django.views import View
from Shop.user.forms import RegisterModelForm, LoginModelForm
from Shop.user import set_password


# 定义注册页面的视图类
class RegisterView(View):

    def get(self, request):
        # 跳转注册表单
        return render(request, 'user/reg.html')

    def post(self, request):  # 注册页面视图
        # 接收参数
        data = request.POST
        # 表单验证合法
        form = RegisterModelForm(data)
        if form.is_valid():
            # 操作数据库
            clened_data = form.cleaned_data
            # 创建一个用户
            user = Users()
            user.user_name = clened_data.get('user_name')
            user.password = set_password(clened_data.get('password'))
            user.save()
            return redirect('user:登录')
        # 错误
        else:
            return render(request, 'user/login.html', context={'form': form})


# 定义登录页面的视图类
class LoginView(View):
    def get(self, request):
        # 跳转登录页面
        return render(request, 'user/login.html')

    def post(self, request):
        # 接收参数
        data = request.POST
        # 表单验证合法
        form = LoginModelForm(data)
        if form.is_valid():
            user = form.cleaned_data.get('user')
            request.session['ID'] = user.pk
            request.session['user_name'] = user.user_name
            return redirect('item:主页')
        else:
            return render(request, 'user/login.html', context={'form': form})

Shop/templates/user/collect-edit.html
{% extends 'common/parent.html' %}
{% load static %}


{% block content %}

    <body>
		<header data-am-widget="header" class="am-header am-header-default sq-head ">
			<div class="am-header-left am-header-nav">
				<a href="javascript:history.back()" class="">
					<i class="am-icon-chevron-left"></i>
				</a>
			</div>
			<h1 class="am-header-title">
  	            <a href="" class="">编辑</a>
            </h1>
            <div class="am-header-right am-header-nav">
			    <a href="" class="">
		        完成
		        </a>
			</div>
	    </header>
	    <div style="height: 49px;"></div>
	    <ul class="list-pro" style="margin-top: 0;">
	    	<li>
	    		<label class="am-checkbox am-warning"  style="float: left; width: 5%; margin-top: 3.5rem;">
                 <input type="checkbox" checked="checked" value="" data-am-ucheck checked>
                </label>
	    		<a href="{% url 'com:商品详情' %}"><img src="{% static 'images/test10.png' %}" class="list-pic" /></a>
	    		<div class="shop-list-mid" style="width: 60%;">
                	<div class="tit"><a href="{% url 'com:商品详情' %}">法国加力果12个装 进口新鲜水果 嘎啦苹果 包邮</a></div>
                	<div class="am-gallery-desc">￥52</div>
                	<p>销量：5件</p>
                </div>
	    	</li>
	        <li>
	    		<label class="am-checkbox am-warning"  style="float: left; width: 5%; margin-top: 3.5rem;">
                 <input type="checkbox" checked="checked" value="" data-am-ucheck checked>
                </label>
	    		<a href="{% url 'com:商品详情' %}"><img src=" {% static 'images/test10.png' %}" class="list-pic" /></a>
	    		<div class="shop-list-mid" style="width: 60%;">
                	<div class="tit"><a href="{% url 'com:商品详情' %}">法国加力果12个装 进口新鲜水果 嘎啦苹果 包邮</a></div>
                	<div class="am-gallery-desc">￥52</div>
                	<p>销量：5件</p>
                </div>
	    	</li>
	    	<li>
	    		<label class="am-checkbox am-warning"  style="float: left; width: 5%; margin-top: 3.5rem;">
                 <input type="checkbox" checked="checked" value="" data-am-ucheck checked>
                </label>
	    		<a href="{% url 'com:商品详情' %}"><img src=" {% static 'images/test10.png' %}" class="list-pic" /></a>
	    		<div class="shop-list-mid" style="width: 60%;">
                	<div class="tit"><a href="{% url 'com:商品详情' %}">法国加力果12个装 进口新鲜水果 嘎啦苹果 包邮</a></div>
                	<div class="am-gallery-desc">￥52</div>
                	<p>销量：5件</p>
                </div>
	    	</li>

	    </ul>


	    		<!--底部-->
 <div style=" height: 55px;"></div>
 <ul class="fix-shopping">
 	<li><a href="{% url 'cart:购物车' %}" class="join">加入购物车</a></li>
 	<li><a href="{% url 'order:确认订单' %}" class="imm-buy">立即购买</a></li>
 </ul>




<script>
	//购物数量加减
	$(function(){
		$('.increase').click(function(){
			var self = $(this);
			var current_num = parseInt(self.siblings('input').val());
			current_num += 1;
			self.siblings('input').val(current_num);
			update_item(self.siblings('input').data('item-id'));
		})
		$('.decrease').click(function(){
			var self = $(this);
			var current_num = parseInt(self.siblings('input').val());
			if(current_num > 1){
				current_num -= 1;
				self.siblings('input').val(current_num);
				update_item(self.siblings('input').data('item-id'));
			}
		})
	})
</script>
<script src="{% static 'js/jquery.min.js' %}"></script>
<script src="{% static 'js/amazeui.min.js' %}"></script>
	</body>

{% endblock %}

Shop/templates/user/member.html
{% extends 'common/parent.html' %}
{% load static %}

{% block content %}

    <body style="background: #f6f6f6;">
		<header data-am-widget="header" class="am-header am-header-default sq-head ">
			<h1 class="am-header-title">
  	            <a href="" class="">个人中心</a>
            </h1>
	    </header>
	    <div style="height: 49px;"></div>
	    <div class="member">
	    	<div class="mem-tit">{{ request.session.phone }}
	    		<a href="{% url 'user:系统设置' %}" class="step"><img src="{% static 'images/step.png' %}" width="26"/></a>
	    	</div>
	    	<div class="mem-pic">
		    	<div class="mem-pic-bg" style="background-image: url({{ MEDIA_URL }}{{ request.session.head }});"></div>
	    	</div>
	    	<ul class="member-menu">
			<li>
				<a href="{% url 'user:账户余额' %}">
					<p class="yellow">0</p>
					<p class="black">帐户余额 </p>
				</a>
			</li>
            <li>
				<a href="{% url 'user:积分' %}">
					<p class="yellow">0</p>
					<p class="black">积分 </p>
				</a>
			</li>
			<li>
				<a href="{% url 'com:红包' %}">
					<p class="yellow">0</p>
					<p class="black">优惠劵 </p>
				</a>
			</li>
			<li>
				<a href="{% url 'user:我的收藏' %}">
					<p class="yellow">0</p>
					<p class="black">我的收藏 </p>
				</a>
			</li>
		</ul>
	    </div>
	    <div class="user-list">
		  	<div class="u-list-main">
		  		<img src="{% static 'images/order-pic.png' %}" width="27" />
		  		<span>我的购物订单</span>
		  		<a href="{% url 'order:全部订单' %}">查看全部订单></a>
		  	</div>
		    <ul class="user-nav">
		    	<li><a href="{% url 'order:全部订单' %}"> <img src="{% static 'images/1-icon.png' %}"> <p>待付款</p></a></li>
		    	<li><a href="{% url 'order:全部订单' %}"> <img src="{% static 'images/1-icon1.png' %}"> <p>待收货</p></a></li>
		    	<li><a href="{% url 'order:全部订单' %}"> <img src="{% static 'images/1-icon2.png' %}"> <p>待评价</p></a></li>
		    	<li><a href="{% url 'order:全部订单' %}"> <img src="{% static 'images/1-icon3.png' %}"> <p>退换货</p></a></li>
		    </ul>
		    <div class="u-list-main">
		  		<img src="{% static 'images/order-my.png' %}" width="27" />
		  		<span>帐户与安全</span>
		  	</div>
		    <ul class="user-nav">
		    	<li><a href="{% url 'user:个人资料' %}"> <img src="{% static 'images/1-icon4.png' %}"> <p>个人资料</p></a></li>
		    	<li><a href="{% url 'user:收货地址' %}"> <img src="{% static 'images/1-icon5.png' %}"> <p>收货地址</p></a></li>
		    	<li><a href="{% url 'user:安全设置' %}"> <img src="{% static 'images/1-icon6.png' %}"> <p>安全设置</p></a></li>
		    	<li><a href="{% url 'user:我的钱包' %}"> <img src="{% static 'images/1-icon7.png' %}"> <p>我的钱包</p></a></li>
		    </ul>
	    </div>
	    <!--导航-->
 <ul class="sq-nav" style=" background: #fff; margin-top: 1rem; border-top: 1px solid #ddd;  border-bottom: 1px solid #ddd;">
      <li>
        <div class="am-gallery-item">
            <a href="{% url 'user:我要兼职' %}" class="">
              <img src="{% static 'images/m_03.png' %}" />
              <p>我要兼职</p>
            </a>
        </div>
      </li>
      <li>
        <div class="am-gallery-item">
            <a href="{% url 'user:推荐有奖' %}" class="">
              <img src="{% static 'images/m_04.png' %}" />
              <p>推荐有奖</p>
            </a>
        </div>
      </li>
      <li>
        <div class="am-gallery-item">
            <a href="{% url 'user:我的推荐' %}" class="">
              <img src="{% static 'images/m_05.png' %}" />
              <p>我的推荐</p>
            </a>
        </div>
      </li>
      <li>
        <div class="am-gallery-item">
            <a href="" class="">
              <img src="{% static 'images/m_06.png' %}" />
              <p>我的佣金</p>
            </a>
        </div>
      </li>
      <li>
        <div class="am-gallery-item">
            <a href="{% url 'com:红包' %}" class="">
              <img src="{% static 'images/m_02.png' %}" />
              <p>我的红包</p>
            </a>
        </div>
      </li>
      <li>
        <div class="am-gallery-item">
            <a href="{% url 'user:动态' %}" class="">
              <img src="{% static 'images/m_07.png' %}" />
              <p>我的动态</p>
            </a>
        </div>
      </li>
      <li>
        <div class="am-gallery-item">
            <a href="javascript:;" class="index-qd">
              <img src="{% static 'images/m_08.png' %}" />
              <p>客服中心</p>
            </a>
        </div>
      </li>
      <li>
        <div class="am-gallery-item">
            <a href="{% url 'user:登录' %}" class="">
              <img src="{% static 'images/m_09.png' %}" />
              <p>安全退出</p>
            </a>
        </div>
      </li>
      </ul>
      </div>
    <!--客服中心-->
<div class="qd-box">
	<div class="popup-title">
			<span>客服中心</span>
			<div class="popup-close"><i class="iconfont">&#xe602</i></div>
	</div>
	<div class="dq-text">
		<a href="http://wpa.qq.com/msgrd?v=3&uin=123456789&site=qq&menu=yes">
			<img src="{% static 'images/contactqq.png' %}" width="50" />
			<p class="contactqq">联系QQ</p>
		</a>
		<a href="tel:0791-12345678">
			<img src="{% static 'images/contacttele.png' %}"  width="50" />
			<p class="contacttele">呼叫电话</p>
		</a>
	</div>
</div>
<!--客服中心-->
      <!--底部-->
 <div style="height: 55px;"></div>
 <div data-am-widget="navbar" class="am-navbar am-cf am-navbar-default sq-foot am-no-layout" id="">
      <ul class="am-navbar-nav am-cf am-avg-sm-5">
          <li>
            <a href="{% url 'com:首页' %}" class="">
                <span class="am-icon-home"></span>
                <span class="am-navbar-label">首页</span>
            </a>
          </li>
          <li>
            <a href="{% url 'user:动态' %}" class="">
                <span class="am-icon-comments"></span>
                <span class="am-navbar-label">动态</span>
            </a>
          </li>
          <li>
            <a href="{% url 'cart:购物车' %}" class="">
                <span class="am-icon-shopping-cart"></span>
                <span class="am-navbar-label">购物车</span>
            </a>
          </li>
          <li>
            <a href="{% url 'order:全部订单' %}" class="">
                <span class="am-icon-file-text"></span>
                <span class="am-navbar-label">订单</span>
            </a>
          </li>

          <li>
            <a href="{% url 'user:我的详情' %}" class="curr">
                <span class="am-icon-user"></span>
                <span class="am-navbar-label">我的</span>
            </a>
          </li>
      </ul>
</div>




 <script type='text/javascript'>
	(function(){
		 new PopUp_api({el:'.index-qd',html:'.qd-box'});
	})()
</script>

<script src="{% static 'js/jquery.min.js' %}"></script>
<script src="{% static 'js/amazeui.min.js' %}"></script>
	</body>

{% endblock %}

Shop/templates/user/release.html
{% extends 'common/parent.html' %}
{% load static %}

{% block content %}

    <body style="background: #EFEFEF;">
		<header data-am-widget="header" class="am-header am-header-default sq-head ">
			<div class="am-header-left am-header-nav">
				<a href="{% url 'user:动态' %}" class="">
					取消
				</a>
			</div>
			<h1 class="am-header-title">
  	            <a href="" class="">发布动态</a>
            </h1>
            <div class="am-header-right am-header-nav">
				<a href="{% url 'user:发布动态' %}" class="">
					发布
				</a>
			</div>
	    </header>
	    <div style="height: 49px;"></div>
	    <textarea placeholder="请输入您要发布的内容" class="releasecon"></textarea>
	    <ul class="release-action">
	    	<li>
	    		<span>活动时间：</span>
	    		<input type="text" />
	    	</li>
	    	<li>
	    		<span>活动地点：</span>
	    		<input type="text" />
	    	</li>
	    	<li>
	    		<span>活动人数：</span>
	    		<input type="text" />
	    	</li>
	    </ul>
	</body>

{% endblock %}